---
- hosts: vmnodes
  name: set up basics
  become: yes
  tasks:
#    - name: install python-apt so native apt plugins work
#      package:
#        name: python-apt
#        state: present

    - name: remove file with breaking enterprise repo
      file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: install python-apt so native apt plugins work
      package:
        name: python-apt
        state: present

    - name: disable enterprise repo
      apt_repository:
        repo: deb https://enterprise.proxmox.com/debian/pve buster pve-enterprise
        state: absent
        
    - name: enable community repo
      apt_repository:
        repo: deb http://download.proxmox.com/debian/pve buster pve-no-subscription
        state: present

    - name: Update all packages to the latest version
      apt:
        upgrade: dist


- hosts: lab01.v.ignum.cz
  name: setup ceph specifics
  become: yes
  tasks:
    - name: install Ceph dashboard
      package:
        name: ceph-mgr-dashboard
        state: present

    - name: enable dashboard
      shell: ceph mgr module enable dashboard

    - name: setup dashboard cert
      shell: ceph dashboard create-self-signed-cert

    - name: set dashboard username
      shell: ceph dashboard ac-user-create root showmeceph administrator
