---
- hosts: taz.v.ignum.cz
  name: prepare vtoy master
  become: yes
  vars:
     ipv4_addr: 62.109.152.16
     ipv6_addr: 2001:1ab0:10:100::1:20
  tasks:
    - name: disable cloud-init
      file:
        path: /etc/cloud/cloud-init.disabled
        state: touch
        mode: '644'
        modification_time: preserve
        access_time: preserve

    - name: remove debian cloud-init user
      user:
        name: debian
        state: absent
        remove: yes

    - name: install basic utils
      apt:
        name:
          - wget
          - iputils-ping
          - procps
          - vim
          - sudo
          - nftables
          - tcpdump
          - bmon
          - htop
          - qemu-guest-agent
        state: present
        update_cache: yes

    - name: install DHCP infrastructure
      apt:
        name:
          - isc-dhcp-server
        state: present

    - name: setup DHCP
      copy:
        dest: /etc/dhcp/dhcpd.conf
        content: |
          ddns-update-style none;
          default-lease-time 600;
          max-lease-time 7200;
          
          allow booting;
          
          option arch code 93 = unsigned integer 16;
          
          subnet 62.109.152.0 netmask 255.255.248.0 {
             range 62.109.152.10 62.109.152.15;
             option routers 62.109.152.1;
             option domain-name-servers 217.31.53.53;
             option domain-name "v.ignum.cz";
             allow unknown-clients;
          }
 
    - name: setup DHCPv6
      copy:
        dest: /etc/dhcp/dhcpd6.conf
        content: |
          default-lease-time 2592000;
          preferred-lifetime 604800;
          option dhcp-renewal-time 3600;
          option dhcp-rebinding-time 7200;

          allow leasequery;

          option dhcp6.name-servers 2001:1ab0:b0f4:53::53;
          option dhcp6.domain-search "v.ignum.cz","ignum.cz";

          subnet6 2001:1ab0:10:100::/64 {
            range6 2001:1ab0:10:100::1:100 2001:1ab0:10:100::1:ffff;
          }

    - name: set dhcp listen interfaces IPv4
      lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^INTERFACESv4='
        line: 'INTERFACESv4="eth0"'

    - name: set dhcp listen interfaces IPv6
      lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^INTERFACESv6='
        line: 'INTERFACESv6="eth0"'

    - name: restart isc-dhcp-server
      service:
        name: isc-dhcp-server
        state: restarted
        enabled: yes

    - name: setup firewall
      copy:
        dest: /etc/nftables.conf
        content: |
          #!/usr/sbin/nft -f

          flush ruleset

          table inet filter {
            chain input {
              type filter hook input priority 0; policy drop;

              ct state {established, related} counter accept
              ct state invalid counter drop

              iifname lo accept

              # allow icmp
              ip protocol icmp counter accept
              icmpv6 type {destination-unreachable, packet-too-big, time-exceeded, echo-request, echo-reply, mld-listener-query, mld-listener-report, mld-listener-reduction, nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, nd-redirect, parameter-problem, router-renumbering} accept

              # allow ssh
              tcp dport ssh counter accept

              # allow http and https
              tcp dport {http,https} counter accept


              # allow DHCP
              udp dport bootps counter accept

              # allow traceroute
              udp dport 33434-33524 counter accept

              # allow icinga2 monitoring
              ip saddr 62.109.128.141 tcp dport 5665 counter accept
              ip saddr 62.109.128.141 tcp dport 22 counter accept
            }

            chain forward {
              type filter hook forward priority 0; policy drop;
            }

            chain output {
              type filter hook output priority 0; policy accept;
            }
          }

    - name: restart nft
      service:
        name: nftables.service
        state: restarted
        enabled: yes




